# permissions for end users to edit monitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autodeploy
    app.kubernetes.io/managed-by: kustomize
  name: monitoring-editor-role
rules:
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - monitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - monitorings/status
  verbs:
  - get
